### ISSUE TITLE
[Feature Request] Symfony Bundle

### ISSUE THREAD

**Issue by MrSpoocy** [thephpleague/commonmark#946]
### Description

Right away, I would make a pull request for it ;)

I would like to create a bundle for Symfony (from version 5.4+), so that everything can be set via a yaml file. You would have to create a repository thephpleague/commonmark-bundle. I would then make a pull request there (may take a while).

### Example

`config/packages/commonmark.yml`

```yaml
commonmark:
  renderer:
    block_separator: "\n"
    inner_separator: "\n"
    soft_break: "\n"

  commonmark:
    enable_em: true
  html_input: 'escape'
  allow_unsafe_links: false

when@dev:
  commonmark:
    allow_unsafe_links: true
    
when@prod:
  commonmark:
    html_input: 'remove'
```

### Did this project help you today? Did it make you happy in any way?

I think it's very good how open you are with suggestions and how quickly you respond! And I'm always trying to help you via pull request.
